version: '3.8'

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./logs:/usr/src/app/logs
      - ./income:/usr/src/app/income
      - ./outcome:/usr/src/app/outcome

