version: '3'
services:
  bot:
    build: .
    container_name: bot
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    ports:
      - 4444:4444
    networks:
      - bot-network

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    networks:
      - bot-network

networks:
  bot-network:
