version: '3.8'

services:
  selenium-chrome:
    image: selenium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app  
      - /usr/src/app/.venv  
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_URL=http://selenium-chrome:4444/wd/hub
    command: watchmedo auto-restart --patterns="*.py" --recursive -- python bot.py  
