version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.venv  
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_URL=${SELENIUM_URL}
      - CHROME_NO_SANDBOX=${CHROME_NO_SANDBOX}
      - CHROME_DISABLE_DEV_SHM=${CHROME_DISABLE_DEV_SHM}
    command: watchmedo auto-restart --patterns="*.py" --recursive -- python bot.py
