version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app  # Монтируем локальный каталог в контейнер
      - /usr/src/app/.venv  # Сохраняем виртуальное окружение внутри контейнера
    command: python bot.py  # Запускаем бота
