global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'selenium'
    metrics_path: /wd/hub/status
    static_configs:
      - targets: ['control.smartsoltech.kr:4444']

  - job_name: 'grafana'
    static_configs:
      - targets: ['control.smartsoltech.kr:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['control.smartsoltech.kr:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['control.smartsoltech.kr:9090']
