global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'docker_services'
    static_configs:
      - targets: ['selenium-chrome:4444']

  - job_name: 'bot'
    static_configs:
      - targets: ['bot:5000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
      
