global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'selenium'
    static_configs:
    metrics_path: /wd/hub/status
      - targets: ['selenium-chrome:4444']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
